apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: nabal1114/onedb
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
        resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: db-nfs